### PR TITLE
Support Internet Explorer (avoid setting __proto__)

### PR DESCRIPTION
**Pull request by shebson**
By setting Router.prototype instead of Router.prototype.**proto**, the example app now works in IE9 and IE10.

A mutable **proto** won't be supported by Internet Explorer until the release of IE11, and is not a part of the ES5 standard.

### CODE REVIEW

**Comment by spikebrehm** [comment]
I believe this is not the correct way to setup prototypical inheritance; we'd have to do a bit more, like create a temporary object with the same prototype but an empty constructor, and then `Router.prototype = new Tmp`.

I would accept a PR that uses something like this:

https://github.com/isaacs/inherits

**Comment by spikebrehm** [comment]
@shebson what do you think about this approach?

https://github.com/airbnb/rendr-app-template/pull/51

**Comment by shebson** [comment]
@spikebrehm Love it. #51 strikes me as a much better way to do cross-browser classical inheritance. Tested it and it works in IE10.

**Comment by spikebrehm** [comment]
Cool! Thanks for testing @shebson!

**Pull request closed without merging**
